### ISSUE TITLE
Issue with image size in Flipper component

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-flipper#1]
We have an issue with the flipper component when an image is added to the component.
I have attached an export from a course we're working on.

### The issue

When an image is used, the size of the image is adjusted to the size of the block. From what I can see, this is down based on max-width, rather than width and height. For example see:
  - Example 1
    - Menu Item: Cloudya
    - Page: Cloudya Overview
    - Article: What is Cloudya?
    - Flipper Component: What is it?
    - Original image size is 900px x 600px
    - Reduced to: 864px x 576 px
  - Example 2
    - Menu Item: Cloudya
    - Page: Additional Services for Cloudya
    - Article: Cloudya: The App Suite
    - Block: Cloudya Mobile App for Apple iPhone
    - Flipper Component: Key features
    - Original image size is 230px x 498px
    - **Increased** to: 414px x 896 px
 
### The problem

The image in example 2 is far too big. This results in the component block size being taller than the page. I have tried to add a max-height in custom CSS, but the aspect ratio is not correct and the image is distorted.

### Attempt to fix

I have tried to reduce the maximum height of the component block by using the custom CSS below

```css
.flipper-inner .flipper-container {max-height: 85vh; overflow: auto;}
```

### Requests

- Can we ensure that the component size is not taller than the user screen?
- Can we find a way for image sizes not to increase beyond their original size?
  - *Reduction of images would be acceptable*
- Could we move the DIV with class `flipper-item-instruction` to above the image?
  - *This way if the image really is that tall, then at least the instruction appears above it*
  - *Happy to have a scroll bar added, so if there is really too much content to fit on the available height, then users would need to scroll*
[nfon-portfolio-uk-foundation-export.zip](https://github.com/saga-nfon/adapt-flipper/files/5898362/nfon-portfolio-uk-foundation-export.zip)
[]([nfon-portfolio-uk-foundation-export.zip](https://github.com/saga-nfon/adapt-flipper/files/5898363/nfon-portfolio-uk-foundation-export.zip))

[nfon-portfolio-uk-foundation-export.zip](https://github.com/saga-nfon/adapt-flipper/files/5898365/nfon-portfolio-uk-foundation-export.zip)

**Comment by nfon-christophe** [comment]
Can the scroll bar appearing on the side be removed if not needed?

![Screenshot 2021-02-24 193503](https://user-images.githubusercontent.com/54438034/109055871-9ed90100-76d7-11eb-83b1-469703fa579e.png)

**Comment by hardikforall** [comment]
I have updated the Flipper item height over flow(i.e. overflow-y to auto). now scroll will appear to only places where content is crossing the max height

**Comment by hardik-sagacity** [comment]
I have updated the Flipper item height over flow(i.e. overflow-y to auto). now scroll will appear to only places where content is crossing the max height

**Comment by nfon-christophe** [comment]
Fixed
